### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by DrunkenPoney** [ghostiam/binstruct#2]
Would be nice to have a benchmark comparison with other libraries (e.g. [lunixbochs/struc](https://github.com/lunixbochs/struc))

I'd like to know if this repo offers better performances

**Comment by ghostiam** [comment]
Thank you for your interest in the project.
I think [lunixbochs/struc](https://github.com/lunixbochs/struc) and [ghostiam/binstruct](https://github.com/ghostiam/binstruct) solve different problems, so I see no reason to compare them.

Binstruct was created for parsing (reverse engineering) unknown binary formats (non-writable).

The differences that I see:
**struc**:
- Allows you to both read binary files and write them.

**binstruct**:
- Read-only.
- Wrapper over "encoding/binary" that allows you to read data manually ([readme](https://github.com/ghostiam/binstruct#or-just-use-reader-without-mapping-data-into-the-structure)).
- Offset support ([example](https://github.com/ghostiam/binstruct/blob/master/binstruct_test.go#L17-L19)).
- Calculated lengths and offsets ([readme](https://github.com/ghostiam/binstruct#tags)).
- Support for methods for manual parsing of binary data ([example](https://github.com/ghostiam/binstruct/blob/master/example01_test.go#L18)).

As you can see, "binstruct" allows more control over what and how you read in.
I'm not sure if you can read the PNG format with the "struc" library as easily as it does with "binstruct" library ([example](https://github.com/ghostiam/binstruct/blob/master/examples/png/main.go)).

If you just need to store/read binary data, your choice is "struc", if you need to parse a binary format with a complex structure, your choice is "binstruct".

Before I started creating this library, I rummaged all over Google in search of a suitable solution, unfortunately I did not find anything that would suit my tasks.
