### ISSUE TITLE
Allow referencing inner fields via length tag

### ISSUE THREAD

**Issue by Zekfad** [ghostiam/binstruct#7]
Hi, thank you for this awesome package!

It would be great to add support for referencing inner fields (e.g. I have `Header.EntriesCount`), currently hat requires to write helper method or helper field.

Related code:

https://github.com/ghostiam/binstruct/blob/09ba9cdb76f62a7f80d4843625dd219d339c4659/tag.go#L201C25-L201C36

**Comment by Zekfad** [comment]
Hi. Parent access would be cool, but I'd like to have at least child subfield access, e.g. Field.ChildField

**Comment by ghostiam** [comment]
@Zekfad, please check version v1.3.3
`go get -u github.com/ghostiam/binstruct@latest`

**Comment by Zekfad** [comment]
Working as a charm, thank you very much for a quick update!
